"""add compensation tables

Revision ID: 217f3522ba45
Revises: 297e9727decc
Create Date: 2026-09-29 17:31:05.880905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '217f3522ba45'
down_revision: Union[str, None] = '297e9727decc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compensation_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('compensation_type', sa.Enum('BASE_SALARY', 'BONUS', 'ALLOWANCE', 'COMMISSION', name='compensation_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('frequency', sa.Enum('HOURLY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'ANNUAL', 'ONE_TIME', name='compensation_frequency'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compensation_records_tenant_id'), 'compensation_records', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_compensation_records_worker_id'), 'compensation_records', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compensation_records_worker_id'), table_name='compensation_records')
    op.drop_index(op.f('ix_compensation_records_tenant_id'), table_name='compensation_records')
    op.drop_table('compensation_records')
    # ### end Alembic commands ###
