"""add workers documents agreements tables

Revision ID: 297e9727decc
Revises: 0001_tenants_users
Create Date: 2026-09-19 17:40:08.318227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297e9727decc'
down_revision: Union[str, None] = '0001_tenants_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('work_location', sa.String(length=255), nullable=True),
    sa.Column('worker_type', sa.Enum('EMPLOYEE', 'CONTRACTOR', name='worker_type'), nullable=False),
    sa.Column('status', sa.Enum('ONBOARDING', 'ACTIVE', 'ON_LEAVE', 'OFFBOARDING', 'TERMINATED', name='worker_status'), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['workers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_manager_id'), 'workers', ['manager_id'], unique=False)
    op.create_index(op.f('ix_workers_tenant_id'), 'workers', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workers_user_id'), 'workers', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('PASSPORT', 'VISA', 'WORK_PERMIT', 'TAX_FORM', 'ID_CARD', 'PROOF_OF_ADDRESS', 'BACKGROUND_CHECK', 'OTHER', name='document_type'), nullable=False),
    sa.Column('status', sa.Enum('REQUIRED', 'UPLOADED', 'VERIFIED', 'REJECTED', 'EXPIRED', name='document_status'), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_documents_worker_id'), 'documents', ['worker_id'], unique=False)
    op.create_table('agreements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('agreement_type', sa.Enum('EMPLOYMENT_CONTRACT', 'CONTRACTOR_AGREEMENT', 'NDA', 'AMENDMENT', 'OTHER', name='agreement_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'INTERNAL_REVIEW', 'APPROVED', 'SENT', 'SIGNED', 'ACTIVE', 'EXPIRING', 'RENEWED', 'TERMINATED', name='agreement_status'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('terminated_reason', sa.String(length=1000), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agreements_document_id'), 'agreements', ['document_id'], unique=False)
    op.create_index(op.f('ix_agreements_tenant_id'), 'agreements', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_agreements_worker_id'), 'agreements', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agreements_worker_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_tenant_id'), table_name='agreements')
    op.drop_index(op.f('ix_agreements_document_id'), table_name='agreements')
    op.drop_table('agreements')
    op.drop_index(op.f('ix_documents_worker_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_workers_user_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_tenant_id'), table_name='workers')
    op.drop_index(op.f('ix_workers_manager_id'), table_name='workers')
    op.drop_table('workers')
    sa.Enum(name='agreement_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='agreement_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='document_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='document_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='worker_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='worker_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
